import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ApolloClient, InMemoryCache, gql } from "@apollo/client";

export default function Home({ launches }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img
          src="https://images.unsplash.com/photo-1517976547714-720226b864c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
          alt=""
          className={styles.headerImage}
        />
        <h1 className={styles.title}>Space X Launches</h1>

        <p className={styles.description}>
          Get all sorts of information about previous Space X launches, like
          information about the rocket, astronauts, and more!
        </p>

        <div className={styles.sectionHeading}>
          <h2>Recent Launches</h2>
        </div>

        <div className={styles.grid}>
          {launches.map((launch) => {
            return (
              <a
                key={launch.id}
                href={launch.links.article_link}
                className={styles.card}
              >
                <h2>Project {launch.mission_name}</h2>
                <p>
                  <strong>
                    Launch Date <span> - </span>
                  </strong>
                  {new Date(launch.launch_date_local).toLocaleDateString(
                    "en-IN"
                  )}
                </p>
                <div>
                  <h3>Rocket Name - {launch.rocket.rocket_name}</h3>
                  <h3>Company - {launch.rocket.rocket.company}</h3>
                  <h3>Country - {launch.rocket.rocket.country}</h3>
                  <h3 className={styles.desc}>
                    Description - {launch.rocket.rocket.description}
                  </h3>
                </div>
              </a>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: "https://spacex-production.up.railway.app/",
    cache: new InMemoryCache(),
  });
  const { data } = await client.query({
    query: gql`
      query GetLaunches {
        launchesPast(limit: 12) {
          id
          mission_name
          launch_date_local
          launch_site {
            site_name_long
          }
          links {
            article_link
            video_link
            mission_patch
          }
          rocket {
            rocket_name
            rocket {
              company
              country
              description
            }
          }
        }
      }
    `,
  });
  return {
    props: {
      launches: data.launchesPast,
    },
  };
}
